### ISSUE TITLE
Convert cross references

### ISSUE THREAD

**Issue by jmccrae** [elexis-eu/tei2ontolex#10]
First, we should support the conversion of `<xr>` with a target, e.g.,

```xml
<entry xml:id="borcht" xml:lang="nl">
 <form type="lemma">
  <orth>borcht</orth>
 </form>
 <xr type="related">
  <lbl>Cf.</lbl>
  <ref xml:lang="nl"
   target="#M012340">burcht</ref>
 </xr>
</entry>
```

As 

```turtle
<#borcht> a ontolex:LexicalEntry ;
  ontolex:canonicalForm [ ontolex:writtenRep "borcht"@nl ]
  lexinfo:relatedTerm <#M012340> .
```

**Comment by laurentromary** [comment]
Can you suggest the form for an XML serialization? :-}

**Comment by laurentromary** [comment]
What about  this?
```XML
<lexinfo:relatedTerm rdf:about="#M012340">
         <rdf:Description>
            <rdf:value xml:lang="nl">burcht</rdf:value>
         </rdf:Description>
</lexinfo:relatedTerm>      
```

**Comment by laurentromary** [comment]
I have added the other values from the `<xr>` examples. Once the output syntax is checked, we should be set here.

**Comment by jmccrae** [comment]
Sorry, it seems that I made a mistake, the `rdf:about` attribute is on the wrong tag. It should be:

```
<lexinfo:relatedTerm>
         <rdf:Description rdf:about="#M012340">
            <rdf:value xml:lang="nl">burcht</rdf:value>
         </rdf:Description>
</lexinfo:relatedTerm> 
```

**Comment by laurentromary** [comment]
It's corrected now. Can you check?

**Comment by jmccrae** [comment]
There is still an issue.

```
('<#mero>', '<http://www.w3.org/1999/02/22-rdf-syntax-ns#value>', '""@nl')
('<#hypo>', '<http://www.w3.org/1999/02/22-rdf-syntax-ns#value>', '""@nl')
('<#syn>', '<http://www.w3.org/1999/02/22-rdf-syntax-ns#value>', '""@nl')
('<#hyp>', '<http://www.w3.org/1999/02/22-rdf-syntax-ns#value>', '""@nl')
('<#anto>', '<http://www.w3.org/1999/02/22-rdf-syntax-ns#value>', '""@nl')
```

Basically if there is no text in the `<ref>` tag we shouldn't generate `<rdf:value>`

**Comment by laurentromary** [comment]
This is now corrected!

**Comment by jmccrae** [comment]
Okay, the test passes now
